import Link from "next/link"

export default function Privacy() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-puxa-deepBlue to-puxa-lightBlue text-white">
      <div className="container mx-auto px-4 py-8 md:py-16">
        <h1 className="text-4xl md:text-5xl font-bold mb-8 text-center">Privacy Policy</h1>
        <div className="bg-white/10 backdrop-blur-md rounded-lg shadow-xl p-6 md:p-8 space-y-6">
          <p className="text-sm text-gray-300">Last updated: February 04, 2025</p>
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
            collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">Interpretation and Definitions</h2>
          <h3 className="text-xl font-semibold mt-6 mb-2">Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the following conditions.
            The following definitions shall have the same meaning regardless of whether they appear in singular or in
            plural.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-2">Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              <strong>Account</strong> means a unique account created for You to access our Service or parts of our
              Service.
            </li>
            <li>
              <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with
              a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities
              entitled to vote for election of directors or other managing authority.
            </li>
            <li>
              <strong>Application</strong> refers to Puxa Time, the software program provided by the Company.
            </li>
            <li>
              <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)
              refers to Puxa Time.
            </li>
            <li>
              <strong>Country</strong> refers to: Brazil
            </li>
            <li>
              <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a
              digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to an identified or identifiable
              individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Application.
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of
              the Company. It refers to third-party companies or individuals employed by the Company to facilitate the
              Service, to provide the Service on behalf of the Company, to perform services related to the Service or to
              assist the Company in analyzing how the Service is used.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the
              Service or from the Service infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal
              entity on behalf of which such individual is accessing or using the Service, as applicable.
            </li>
          </ul>

          {/* Add more sections here */}

          <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              By email:{" "}
              <a href="mailto:pedro.oliveira@monteirodev.com" className="text-white hover:text-black">
                pedro.oliveira@monteirodev.com
              </a>
            </li>
            <li>
              By visiting this page on our website:{" "}
              <Link
                href="https://puxatime.vercel.app"
                className="text-white hover:text-black"
                target="_blank"
                rel="noopener noreferrer"
              >
                https://puxatime.vercel.app
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </div>
  )
}

